// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyrpzbormnfznzclynga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cnB6Ym9ybW5mem56Y2x5bmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTYzMjAsImV4cCI6MjA1OTE5MjMyMH0.xidTtRRPeWw1cg1X9VHkCvPIe9dby0MtnXx30iyrI98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);